---
- name: LAB 04
  hosts: host1.example.com
  vars:
    facts_directory: /etc/ansible/facts.d
  tasks:

    - name: Criando diretorio {{ facts_directory }}
      file:
        path: "{{ facts_directory }}"
        state: directory
        mode: '0755'

    - name: Copiando facts para o host
      copy:
        src: cringerlabs.fact
        dest: "{{ facts_directory }}"

